from .symptom import Symptom, decorated_function_registry as symptom_decorated_function_registry
from .diagnosis import Diagnosis, decorated_function_registry as diagnosis_decorated_function_registry
from .item_category import ItemCategory, decorated_function_registry as item_category_decorated_function_registry
from .item_type import ItemType, decorated_function_registry as item_type_decorated_function_registry
from .treatment_item import TreatmentItem, decorated_function_registry as treatment_item_decorated_function_registry
